spring:
  application:
    name: weight-tracker-calendar-backend
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: weight_calendar
    password: weight_calendar
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
