ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER weight_calendar IDENTIFIED BY weight_calendar
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO weight_calendar;
GRANT CREATE TABLE TO weight_calendar;
GRANT CREATE VIEW TO weight_calendar;
GRANT CREATE SEQUENCE TO weight_calendar;
GRANT CREATE TRIGGER TO weight_calendar;
GRANT CREATE PROCEDURE TO weight_calendar;

ALTER USER weight_calendar ACCOUNT UNLOCK;
